services:
    app:
        env_file:
            - .env
        build:
            context: ./environment/app
            dockerfile: Dockerfile
        container_name: vama-mobile-app-dev
        network_mode: "host"
        working_dir: /application
        volumes:
            - .:/application
        stdin_open: true
        tty: true
        restart: unless-stopped
