services:
    app:
        env_file:
            - .env
        container_name: vama-mobile-app-dev
        build: 
            context: ./environment/app
            args:
                USER_ID: ${UID:-1000}
                GROUP_ID: ${GID:-1000}
        network_mode: host
        volumes:
            - ./:/application
        working_dir: /application/${PROJECT_DIR}
        stdin_open: true
        tty: true
        restart: unless-stopped
