services:
    app:
        build: .
        container_name: vama-mobile-app-dev
        network_mode: host
        working_dir: /${PROJECT_DIR:-application}
        volumes:
            - ./${PROJECT_DIR:-application}:/${PROJECT_DIR:-application}
        stdin_open: true
        tty: true
        restart: unless-stopped
